### ISSUE TITLE
Exception after adding two devices

### ISSUE THREAD

**Issue by bustawin** [eReuse/workbench#79]
I added a device, and once it started I added another. The result was the following exception:
```python
Traceback (most recent call last):
  File "erasetor.py", line 373, in <module>
    ErasetorServer()
  File "erasetor.py", line 77, in __init__
    wrapper(self.start)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "erasetor.py", line 98, in start
    self.start_erasetor_process()
  File "erasetor.py", line 92, in start_erasetor_process
    main_menu.display()
  File "erasetor.py", line 138, in display
    devices = self.process.get_list()
  File "erasetor.py", line 364, in get_list
    for device in self.devices:
RuntimeError: dictionary changed size during iteration

Note that not always happens, and I couldn't reproduce the error again.

**Comment by adriass** [comment]
This bug should be fixed with [this commit](https://github.com/eReuse/workbench/commit/04f5ac247603c228ae102aaccde8de490e25d427). When the dictionary size is changed raises an error. Now when the error is raised same function will be called to get a a complete list again.
